services:
  database:
    build:
      context: ./MySQL
      dockerfile: Dockerfile
    container_name: parking
    restart: always
    ports:
      - 5500:3306
    volumes:
      - ./MySQL/data:/var/lib/mysql
    networks:
      - eam_parcial
    healthcheck:
      test: ["CMD","mysql","-u","root","-proot_1234"]
      interval: 30s
      timeout: 10s
      retries: 5
  adminer:
    image: adminer
    container_name: adminer_parcial_parking
    restart: always
    ports:
      - 8000:8080
    networks:
      - eam_parcial
    depends_on:
      database:
        condition: service_healthy

networks:
  eam_parcial:
    driver: bridge
    name: eam_parcial